// Calibration samples extracted from Fuller & Rao, 2017 (Scientific Reports)
// Source: Table 2 — HPLC-measured caffeine concentrations for cold-brew batches.
// These are high-quality `direct_hplc` measurements and suitable as CalibrationSample entries.
import type { CalibrationSample } from "./caffilab";

export const FULLER_RAO_2017_SAMPLES: CalibrationSample[] = [
  {
    id: "fuller-rao-2017-medium-medium",
    source: "Fuller & Rao (2017), Scientific Reports — Table 2 (HPLC)",
    brewMethod: "cold_brew",
    physics: "cold_immersion",
    doseG: 35,
    beverageVolumeMl: 350,
    grindCategory: "medium",
    brewTimeMin: 1440,
    temperatureC: 23.5,
    roastLevel: "medium",
    beanType: "arabica",
    originRegion: "unknown",
    // predictedMg computed from current CaffiLab cold_immersion sub-model
    predictedMg: 383.9,
    // measured value from Table 2: 1180 mg/L × 0.35 L = 413 mg
    measuredMg: 413,
    dataQuality: "direct_hplc",
    notes:
      "Fuller & Rao 2017 — Kona Typica arabica; 35 g coffee in 350 mL water; 24 h; Table 2 HPLC concentration 1180 ± 90 mg/L.",
  },
  {
    id: "fuller-rao-2017-medium-coarse",
    source: "Fuller & Rao (2017), Scientific Reports — Table 2 (HPLC)",
    brewMethod: "cold_brew",
    physics: "cold_immersion",
    doseG: 35,
    beverageVolumeMl: 350,
    grindCategory: "coarse",
    brewTimeMin: 1440,
    temperatureC: 23.5,
    roastLevel: "medium",
    beanType: "arabica",
    originRegion: "unknown",
    predictedMg: 386.2,
    // measured value from Table 2: 1230 mg/L × 0.35 L = 430.5 mg
    measuredMg: 430.5,
    dataQuality: "direct_hplc",
    notes:
      "Fuller & Rao 2017 — Kona Typica arabica; 35 g coffee in 350 mL water; 24 h; Table 2 HPLC concentration 1230 ± 60 mg/L.",
  },
  {
    id: "fuller-rao-2017-dark-medium",
    source: "Fuller & Rao (2017), Scientific Reports — Table 2 (HPLC)",
    brewMethod: "cold_brew",
    physics: "cold_immersion",
    doseG: 35,
    beverageVolumeMl: 350,
    grindCategory: "medium",
    brewTimeMin: 1440,
    temperatureC: 23.5,
    roastLevel: "dark",
    beanType: "arabica",
    originRegion: "unknown",
    predictedMg: 369.3,
    // measured value from Table 2: 1080 mg/L × 0.35 L = 378 mg
    measuredMg: 378,
    dataQuality: "direct_hplc",
    notes:
      "Fuller & Rao 2017 — Kona Typica arabica; dark roast; 35 g coffee in 350 mL water; 24 h; Table 2 HPLC concentration 1080 ± 70 mg/L.",
  },
  {
    id: "fuller-rao-2017-dark-coarse",
    source: "Fuller & Rao (2017), Scientific Reports — Table 2 (HPLC)",
    brewMethod: "cold_brew",
    physics: "cold_immersion",
    doseG: 35,
    beverageVolumeMl: 350,
    grindCategory: "coarse",
    brewTimeMin: 1440,
    temperatureC: 23.5,
    roastLevel: "dark",
    beanType: "arabica",
    originRegion: "unknown",
    predictedMg: 371.6,
    // measured value from Table 2: 990 mg/L × 0.35 L = 346.5 mg
    measuredMg: 346.5,
    dataQuality: "direct_hplc",
    notes:
      "Fuller & Rao 2017 — Kona Typica arabica; dark roast; 35 g coffee in 350 mL water; 24 h; Table 2 HPLC concentration 990 ± 30 mg/L.",
  },
];

export default FULLER_RAO_2017_SAMPLES;

// Stanek et al. 2021 — Cold brew (CB) HPLC measurements (Table 1).
// Values taken from Table 1 (mg/100 g of coffee) and converted to total mg per
// batch using the method described in the paper: 300 g coffee in 5000 mL water.
export const STANEK_2021_CB_SAMPLES: CalibrationSample[] = [
  {
    id: "stanek-2021-gw-cb",
    source: "Stanek et al. (2021), Scientific Reports — Table 1 (HPLC)",
    brewMethod: "cold_brew",
    physics: "cold_immersion",
    doseG: 300,
    beverageVolumeMl: 5000,
    grindCategory: "medium",
    brewTimeMin: 1440,
    temperatureC: 10,
    roastLevel: "medium",
    beanType: "arabica",
    originRegion: undefined,
    predictedMg: 1749.7,
    measuredMg: 2133.0,
    dataQuality: "direct_hplc",
    notes: "Guatemalan (Gw) cold brew — Table 1 value 711 mg/100g; converted to total mg for 300 g batch.",
  },
  {
    id: "stanek-2021-sw-cb",
    source: "Stanek et al. (2021), Scientific Reports — Table 1 (HPLC)",
    brewMethod: "cold_brew",
    physics: "cold_immersion",
    doseG: 300,
    beverageVolumeMl: 5000,
    grindCategory: "medium",
    brewTimeMin: 1440,
    temperatureC: 10,
    roastLevel: "medium",
    beanType: "arabica",
    originRegion: undefined,
    predictedMg: 1643.9,
    measuredMg: 2004.0,
    dataQuality: "direct_hplc",
    notes: "El Salvador (Sw) cold brew — Table 1 value 668 mg/100g; converted to total mg for 300 g batch.",
  },
  {
    id: "stanek-2021-bpn-cb",
    source: "Stanek et al. (2021), Scientific Reports — Table 1 (HPLC)",
    brewMethod: "cold_brew",
    physics: "cold_immersion",
    doseG: 300,
    beverageVolumeMl: 5000,
    grindCategory: "medium",
    brewTimeMin: 1440,
    temperatureC: 10,
    roastLevel: "medium",
    beanType: "arabica",
    originRegion: undefined,
    predictedMg: 1801.4,
    measuredMg: 2196.0,
    dataQuality: "direct_hplc",
    notes: "Brazil pulped natural (Bpn) cold brew — Table 1 value 732 mg/100g; converted to total mg for 300 g batch.",
  },
  {
    id: "stanek-2021-bn-cb",
    source: "Stanek et al. (2021), Scientific Reports — Table 1 (HPLC)",
    brewMethod: "cold_brew",
    physics: "cold_immersion",
    doseG: 300,
    beverageVolumeMl: 5000,
    grindCategory: "medium",
    brewTimeMin: 1440,
    temperatureC: 10,
    roastLevel: "medium",
    beanType: "arabica",
    originRegion: undefined,
    predictedMg: 1735.0,
    measuredMg: 2115.0,
    dataQuality: "direct_hplc",
    notes: "Brazil natural (Bn) cold brew — Table 1 value 705 mg/100g; converted to total mg for 300 g batch.",
  },
  {
    id: "stanek-2021-spn-cb",
    source: "Stanek et al. (2021), Scientific Reports — Table 1 (HPLC)",
    brewMethod: "cold_brew",
    physics: "cold_immersion",
    doseG: 300,
    beverageVolumeMl: 5000,
    grindCategory: "medium",
    brewTimeMin: 1440,
    temperatureC: 10,
    roastLevel: "medium",
    beanType: "arabica",
    originRegion: undefined,
    predictedMg: 1828.5,
    measuredMg: 2229.0,
    dataQuality: "direct_hplc",
    notes: "El Salvador pulped natural (Spn) cold brew — Table 1 value 743 mg/100g; converted to total mg for 300 g batch.",
  },
  {
    id: "stanek-2021-bow-cb",
    source: "Stanek et al. (2021), Scientific Reports — Table 1 (HPLC)",
    brewMethod: "cold_brew",
    physics: "cold_immersion",
    doseG: 300,
    beverageVolumeMl: 5000,
    grindCategory: "medium",
    brewTimeMin: 1440,
    temperatureC: 10,
    roastLevel: "medium",
    beanType: "arabica",
    originRegion: undefined,
    predictedMg: 1488.9,
    measuredMg: 1815.0,
    dataQuality: "direct_hplc",
    notes: "Bolivia washed (BOw) cold brew — Table 1 value 605 mg/100g; converted to total mg for 300 g batch.",
  },
];
