//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  article: Article;
  articleConnection: ArticleConnection;
  project: Project;
  projectConnection: ProjectConnection;
  page: Page;
  pageConnection: PageConnection;
  homepageHero: HomepageHero;
  homepageHeroConnection: HomepageHeroConnection;
  homepageFeaturedProjects: HomepageFeaturedProjects;
  homepageFeaturedProjectsConnection: HomepageFeaturedProjectsConnection;
  homepageSupportCopy: HomepageSupportCopy;
  homepageSupportCopyConnection: HomepageSupportCopyConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryArticleArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryArticleConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ArticleFilter>;
};


export type QueryProjectArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjectConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectFilter>;
};


export type QueryPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
};


export type QueryHomepageHeroArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageHeroConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageHeroFilter>;
};


export type QueryHomepageFeaturedProjectsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageFeaturedProjectsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFeaturedProjectsFilter>;
};


export type QueryHomepageSupportCopyArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageSupportCopyConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageSupportCopyFilter>;
};

export type DocumentFilter = {
  article?: InputMaybe<ArticleFilter>;
  project?: InputMaybe<ProjectFilter>;
  page?: InputMaybe<PageFilter>;
  homepageHero?: InputMaybe<HomepageHeroFilter>;
  homepageFeaturedProjects?: InputMaybe<HomepageFeaturedProjectsFilter>;
  homepageSupportCopy?: InputMaybe<HomepageSupportCopyFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Article | Project | Page | HomepageHero | HomepageFeaturedProjects | HomepageSupportCopy | Folder;

export type Article = Node & Document & {
  __typename?: 'Article';
  title: Scalars['String']['output'];
  excerpt: Scalars['String']['output'];
  date: Scalars['String']['output'];
  category: Scalars['String']['output'];
  primaryCategory: Scalars['String']['output'];
  tags: Array<Scalars['String']['output']>;
  author: Scalars['String']['output'];
  depthLevel?: Maybe<Scalars['String']['output']>;
  coverImage?: Maybe<Scalars['String']['output']>;
  coverAlt?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ArticleFilter = {
  title?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  category?: InputMaybe<StringFilter>;
  primaryCategory?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
  depthLevel?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<StringFilter>;
  coverAlt?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ArticleConnectionEdges = {
  __typename?: 'ArticleConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Article>;
};

export type ArticleConnection = Connection & {
  __typename?: 'ArticleConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ArticleConnectionEdges>>>;
};

export type Project = Node & Document & {
  __typename?: 'Project';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  date: Scalars['String']['output'];
  primaryCategory: Scalars['String']['output'];
  tags: Array<Scalars['String']['output']>;
  depthLevel?: Maybe<Scalars['String']['output']>;
  status: Scalars['String']['output'];
  githubUrl?: Maybe<Scalars['String']['output']>;
  liveUrl?: Maybe<Scalars['String']['output']>;
  coverImage?: Maybe<Scalars['String']['output']>;
  coverAlt?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ProjectFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  primaryCategory?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  depthLevel?: InputMaybe<StringFilter>;
  status?: InputMaybe<StringFilter>;
  githubUrl?: InputMaybe<StringFilter>;
  liveUrl?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<StringFilter>;
  coverAlt?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ProjectConnectionEdges = {
  __typename?: 'ProjectConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Project>;
};

export type ProjectConnection = Connection & {
  __typename?: 'ProjectConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProjectConnectionEdges>>>;
};

export type Page = Node & Document & {
  __typename?: 'Page';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PageFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PageConnectionEdges = {
  __typename?: 'PageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page>;
};

export type PageConnection = Connection & {
  __typename?: 'PageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageConnectionEdges>>>;
};

export type HomepageHeroPrimaryCta = {
  __typename?: 'HomepageHeroPrimaryCta';
  label: Scalars['String']['output'];
  href: Scalars['String']['output'];
};

export type HomepageHeroSecondaryCta = {
  __typename?: 'HomepageHeroSecondaryCta';
  label: Scalars['String']['output'];
  href: Scalars['String']['output'];
};

export type HomepageHeroWhatIDo = {
  __typename?: 'HomepageHeroWhatIDo';
  icon: Scalars['String']['output'];
  label: Scalars['String']['output'];
};

export type HomepageHero = Node & Document & {
  __typename?: 'HomepageHero';
  headline: Scalars['String']['output'];
  identityLine: Scalars['String']['output'];
  subheadline: Scalars['String']['output'];
  primaryCta?: Maybe<HomepageHeroPrimaryCta>;
  secondaryCta?: Maybe<HomepageHeroSecondaryCta>;
  statusLine?: Maybe<Scalars['String']['output']>;
  tagline?: Maybe<Scalars['String']['output']>;
  visualImage?: Maybe<Scalars['String']['output']>;
  visualAlt?: Maybe<Scalars['String']['output']>;
  whatIDo?: Maybe<Array<Maybe<HomepageHeroWhatIDo>>>;
  credentialFootnote?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomepageHeroPrimaryCtaFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type HomepageHeroSecondaryCtaFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type HomepageHeroWhatIDoFilter = {
  icon?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type HomepageHeroFilter = {
  headline?: InputMaybe<StringFilter>;
  identityLine?: InputMaybe<StringFilter>;
  subheadline?: InputMaybe<StringFilter>;
  primaryCta?: InputMaybe<HomepageHeroPrimaryCtaFilter>;
  secondaryCta?: InputMaybe<HomepageHeroSecondaryCtaFilter>;
  statusLine?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  visualImage?: InputMaybe<StringFilter>;
  visualAlt?: InputMaybe<StringFilter>;
  whatIDo?: InputMaybe<HomepageHeroWhatIDoFilter>;
  credentialFootnote?: InputMaybe<StringFilter>;
};

export type HomepageHeroConnectionEdges = {
  __typename?: 'HomepageHeroConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<HomepageHero>;
};

export type HomepageHeroConnection = Connection & {
  __typename?: 'HomepageHeroConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomepageHeroConnectionEdges>>>;
};

export type HomepageFeaturedProjectsProjects = {
  __typename?: 'HomepageFeaturedProjectsProjects';
  slug: Scalars['String']['output'];
  title: Scalars['String']['output'];
  problem: Scalars['String']['output'];
  whyItMatters: Scalars['String']['output'];
  tags: Array<Scalars['String']['output']>;
  thumbnail?: Maybe<Scalars['String']['output']>;
  thumbnailAlt?: Maybe<Scalars['String']['output']>;
  status: Scalars['String']['output'];
  statusColor: Scalars['String']['output'];
};

export type HomepageFeaturedProjects = Node & Document & {
  __typename?: 'HomepageFeaturedProjects';
  projects?: Maybe<Array<Maybe<HomepageFeaturedProjectsProjects>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomepageFeaturedProjectsProjectsFilter = {
  slug?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  problem?: InputMaybe<StringFilter>;
  whyItMatters?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  thumbnail?: InputMaybe<StringFilter>;
  thumbnailAlt?: InputMaybe<StringFilter>;
  status?: InputMaybe<StringFilter>;
  statusColor?: InputMaybe<StringFilter>;
};

export type HomepageFeaturedProjectsFilter = {
  projects?: InputMaybe<HomepageFeaturedProjectsProjectsFilter>;
};

export type HomepageFeaturedProjectsConnectionEdges = {
  __typename?: 'HomepageFeaturedProjectsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<HomepageFeaturedProjects>;
};

export type HomepageFeaturedProjectsConnection = Connection & {
  __typename?: 'HomepageFeaturedProjectsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomepageFeaturedProjectsConnectionEdges>>>;
};

export type HomepageSupportCopy = Node & Document & {
  __typename?: 'HomepageSupportCopy';
  heading: Scalars['String']['output'];
  body: Scalars['String']['output'];
  primaryCtaLabel: Scalars['String']['output'];
  primaryCtaHref: Scalars['String']['output'];
  secondaryCtaLabel: Scalars['String']['output'];
  secondaryCtaHref: Scalars['String']['output'];
  footnote: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomepageSupportCopyFilter = {
  heading?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
  primaryCtaLabel?: InputMaybe<StringFilter>;
  primaryCtaHref?: InputMaybe<StringFilter>;
  secondaryCtaLabel?: InputMaybe<StringFilter>;
  secondaryCtaHref?: InputMaybe<StringFilter>;
  footnote?: InputMaybe<StringFilter>;
};

export type HomepageSupportCopyConnectionEdges = {
  __typename?: 'HomepageSupportCopyConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<HomepageSupportCopy>;
};

export type HomepageSupportCopyConnection = Connection & {
  __typename?: 'HomepageSupportCopyConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomepageSupportCopyConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateArticle: Article;
  createArticle: Article;
  updateProject: Project;
  createProject: Project;
  updatePage: Page;
  createPage: Page;
  updateHomepageHero: HomepageHero;
  createHomepageHero: HomepageHero;
  updateHomepageFeaturedProjects: HomepageFeaturedProjects;
  createHomepageFeaturedProjects: HomepageFeaturedProjects;
  updateHomepageSupportCopy: HomepageSupportCopy;
  createHomepageSupportCopy: HomepageSupportCopy;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateArticleArgs = {
  relativePath: Scalars['String']['input'];
  params: ArticleMutation;
};


export type MutationCreateArticleArgs = {
  relativePath: Scalars['String']['input'];
  params: ArticleMutation;
};


export type MutationUpdateProjectArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectMutation;
};


export type MutationCreateProjectArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectMutation;
};


export type MutationUpdatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationCreatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationUpdateHomepageHeroArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageHeroMutation;
};


export type MutationCreateHomepageHeroArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageHeroMutation;
};


export type MutationUpdateHomepageFeaturedProjectsArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageFeaturedProjectsMutation;
};


export type MutationCreateHomepageFeaturedProjectsArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageFeaturedProjectsMutation;
};


export type MutationUpdateHomepageSupportCopyArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageSupportCopyMutation;
};


export type MutationCreateHomepageSupportCopyArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageSupportCopyMutation;
};

export type DocumentUpdateMutation = {
  article?: InputMaybe<ArticleMutation>;
  project?: InputMaybe<ProjectMutation>;
  page?: InputMaybe<PageMutation>;
  homepageHero?: InputMaybe<HomepageHeroMutation>;
  homepageFeaturedProjects?: InputMaybe<HomepageFeaturedProjectsMutation>;
  homepageSupportCopy?: InputMaybe<HomepageSupportCopyMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  article?: InputMaybe<ArticleMutation>;
  project?: InputMaybe<ProjectMutation>;
  page?: InputMaybe<PageMutation>;
  homepageHero?: InputMaybe<HomepageHeroMutation>;
  homepageFeaturedProjects?: InputMaybe<HomepageFeaturedProjectsMutation>;
  homepageSupportCopy?: InputMaybe<HomepageSupportCopyMutation>;
};

export type ArticleMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  primaryCategory?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  author?: InputMaybe<Scalars['String']['input']>;
  depthLevel?: InputMaybe<Scalars['String']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  coverAlt?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ProjectMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  primaryCategory?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  depthLevel?: InputMaybe<Scalars['String']['input']>;
  status?: InputMaybe<Scalars['String']['input']>;
  githubUrl?: InputMaybe<Scalars['String']['input']>;
  liveUrl?: InputMaybe<Scalars['String']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  coverAlt?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type PageMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type HomepageHeroPrimaryCtaMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageHeroSecondaryCtaMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageHeroWhatIDoMutation = {
  icon?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageHeroMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  identityLine?: InputMaybe<Scalars['String']['input']>;
  subheadline?: InputMaybe<Scalars['String']['input']>;
  primaryCta?: InputMaybe<HomepageHeroPrimaryCtaMutation>;
  secondaryCta?: InputMaybe<HomepageHeroSecondaryCtaMutation>;
  statusLine?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  visualImage?: InputMaybe<Scalars['String']['input']>;
  visualAlt?: InputMaybe<Scalars['String']['input']>;
  whatIDo?: InputMaybe<Array<InputMaybe<HomepageHeroWhatIDoMutation>>>;
  credentialFootnote?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageFeaturedProjectsProjectsMutation = {
  slug?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  problem?: InputMaybe<Scalars['String']['input']>;
  whyItMatters?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  thumbnail?: InputMaybe<Scalars['String']['input']>;
  thumbnailAlt?: InputMaybe<Scalars['String']['input']>;
  status?: InputMaybe<Scalars['String']['input']>;
  statusColor?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageFeaturedProjectsMutation = {
  projects?: InputMaybe<Array<InputMaybe<HomepageFeaturedProjectsProjectsMutation>>>;
};

export type HomepageSupportCopyMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
  primaryCtaLabel?: InputMaybe<Scalars['String']['input']>;
  primaryCtaHref?: InputMaybe<Scalars['String']['input']>;
  secondaryCtaLabel?: InputMaybe<Scalars['String']['input']>;
  secondaryCtaHref?: InputMaybe<Scalars['String']['input']>;
  footnote?: InputMaybe<Scalars['String']['input']>;
};

export type ArticlePartsFragment = { __typename: 'Article', title: string, excerpt: string, date: string, category: string, primaryCategory: string, tags: Array<string>, author: string, depthLevel?: string | null, coverImage?: string | null, coverAlt?: string | null, body?: any | null };

export type ProjectPartsFragment = { __typename: 'Project', title: string, description: string, date: string, primaryCategory: string, tags: Array<string>, depthLevel?: string | null, status: string, githubUrl?: string | null, liveUrl?: string | null, coverImage?: string | null, coverAlt?: string | null, body?: any | null };

export type PagePartsFragment = { __typename: 'Page', title: string, description: string, body?: any | null };

export type HomepageHeroPartsFragment = { __typename: 'HomepageHero', headline: string, identityLine: string, subheadline: string, statusLine?: string | null, tagline?: string | null, visualImage?: string | null, visualAlt?: string | null, credentialFootnote?: string | null, primaryCta?: { __typename: 'HomepageHeroPrimaryCta', label: string, href: string } | null, secondaryCta?: { __typename: 'HomepageHeroSecondaryCta', label: string, href: string } | null, whatIDo?: Array<{ __typename: 'HomepageHeroWhatIDo', icon: string, label: string } | null> | null };

export type HomepageFeaturedProjectsPartsFragment = { __typename: 'HomepageFeaturedProjects', projects?: Array<{ __typename: 'HomepageFeaturedProjectsProjects', slug: string, title: string, problem: string, whyItMatters: string, tags: Array<string>, thumbnail?: string | null, thumbnailAlt?: string | null, status: string, statusColor: string } | null> | null };

export type HomepageSupportCopyPartsFragment = { __typename: 'HomepageSupportCopy', heading: string, body: string, primaryCtaLabel: string, primaryCtaHref: string, secondaryCtaLabel: string, secondaryCtaHref: string, footnote: string };

export type ArticleQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ArticleQuery = { __typename?: 'Query', article: { __typename: 'Article', id: string, title: string, excerpt: string, date: string, category: string, primaryCategory: string, tags: Array<string>, author: string, depthLevel?: string | null, coverImage?: string | null, coverAlt?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ArticleConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ArticleFilter>;
}>;


export type ArticleConnectionQuery = { __typename?: 'Query', articleConnection: { __typename?: 'ArticleConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ArticleConnectionEdges', cursor: string, node?: { __typename: 'Article', id: string, title: string, excerpt: string, date: string, category: string, primaryCategory: string, tags: Array<string>, author: string, depthLevel?: string | null, coverImage?: string | null, coverAlt?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ProjectQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProjectQuery = { __typename?: 'Query', project: { __typename: 'Project', id: string, title: string, description: string, date: string, primaryCategory: string, tags: Array<string>, depthLevel?: string | null, status: string, githubUrl?: string | null, liveUrl?: string | null, coverImage?: string | null, coverAlt?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ProjectConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectFilter>;
}>;


export type ProjectConnectionQuery = { __typename?: 'Query', projectConnection: { __typename?: 'ProjectConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProjectConnectionEdges', cursor: string, node?: { __typename: 'Project', id: string, title: string, description: string, date: string, primaryCategory: string, tags: Array<string>, depthLevel?: string | null, status: string, githubUrl?: string | null, liveUrl?: string | null, coverImage?: string | null, coverAlt?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PageQuery = { __typename?: 'Query', page: { __typename: 'Page', id: string, title: string, description: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
}>;


export type PageConnectionQuery = { __typename?: 'Query', pageConnection: { __typename?: 'PageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PageConnectionEdges', cursor: string, node?: { __typename: 'Page', id: string, title: string, description: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type HomepageHeroQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomepageHeroQuery = { __typename?: 'Query', homepageHero: { __typename: 'HomepageHero', id: string, headline: string, identityLine: string, subheadline: string, statusLine?: string | null, tagline?: string | null, visualImage?: string | null, visualAlt?: string | null, credentialFootnote?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, primaryCta?: { __typename: 'HomepageHeroPrimaryCta', label: string, href: string } | null, secondaryCta?: { __typename: 'HomepageHeroSecondaryCta', label: string, href: string } | null, whatIDo?: Array<{ __typename: 'HomepageHeroWhatIDo', icon: string, label: string } | null> | null } };

export type HomepageHeroConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageHeroFilter>;
}>;


export type HomepageHeroConnectionQuery = { __typename?: 'Query', homepageHeroConnection: { __typename?: 'HomepageHeroConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomepageHeroConnectionEdges', cursor: string, node?: { __typename: 'HomepageHero', id: string, headline: string, identityLine: string, subheadline: string, statusLine?: string | null, tagline?: string | null, visualImage?: string | null, visualAlt?: string | null, credentialFootnote?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, primaryCta?: { __typename: 'HomepageHeroPrimaryCta', label: string, href: string } | null, secondaryCta?: { __typename: 'HomepageHeroSecondaryCta', label: string, href: string } | null, whatIDo?: Array<{ __typename: 'HomepageHeroWhatIDo', icon: string, label: string } | null> | null } | null } | null> | null } };

export type HomepageFeaturedProjectsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomepageFeaturedProjectsQuery = { __typename?: 'Query', homepageFeaturedProjects: { __typename: 'HomepageFeaturedProjects', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, projects?: Array<{ __typename: 'HomepageFeaturedProjectsProjects', slug: string, title: string, problem: string, whyItMatters: string, tags: Array<string>, thumbnail?: string | null, thumbnailAlt?: string | null, status: string, statusColor: string } | null> | null } };

export type HomepageFeaturedProjectsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFeaturedProjectsFilter>;
}>;


export type HomepageFeaturedProjectsConnectionQuery = { __typename?: 'Query', homepageFeaturedProjectsConnection: { __typename?: 'HomepageFeaturedProjectsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomepageFeaturedProjectsConnectionEdges', cursor: string, node?: { __typename: 'HomepageFeaturedProjects', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, projects?: Array<{ __typename: 'HomepageFeaturedProjectsProjects', slug: string, title: string, problem: string, whyItMatters: string, tags: Array<string>, thumbnail?: string | null, thumbnailAlt?: string | null, status: string, statusColor: string } | null> | null } | null } | null> | null } };

export type HomepageSupportCopyQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomepageSupportCopyQuery = { __typename?: 'Query', homepageSupportCopy: { __typename: 'HomepageSupportCopy', id: string, heading: string, body: string, primaryCtaLabel: string, primaryCtaHref: string, secondaryCtaLabel: string, secondaryCtaHref: string, footnote: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type HomepageSupportCopyConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageSupportCopyFilter>;
}>;


export type HomepageSupportCopyConnectionQuery = { __typename?: 'Query', homepageSupportCopyConnection: { __typename?: 'HomepageSupportCopyConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomepageSupportCopyConnectionEdges', cursor: string, node?: { __typename: 'HomepageSupportCopy', id: string, heading: string, body: string, primaryCtaLabel: string, primaryCtaHref: string, secondaryCtaLabel: string, secondaryCtaHref: string, footnote: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const ArticlePartsFragmentDoc = gql`
    fragment ArticleParts on Article {
  __typename
  title
  excerpt
  date
  category
  primaryCategory
  tags
  author
  depthLevel
  coverImage
  coverAlt
  body
}
    `;
export const ProjectPartsFragmentDoc = gql`
    fragment ProjectParts on Project {
  __typename
  title
  description
  date
  primaryCategory
  tags
  depthLevel
  status
  githubUrl
  liveUrl
  coverImage
  coverAlt
  body
}
    `;
export const PagePartsFragmentDoc = gql`
    fragment PageParts on Page {
  __typename
  title
  description
  body
}
    `;
export const HomepageHeroPartsFragmentDoc = gql`
    fragment HomepageHeroParts on HomepageHero {
  __typename
  headline
  identityLine
  subheadline
  primaryCta {
    __typename
    label
    href
  }
  secondaryCta {
    __typename
    label
    href
  }
  statusLine
  tagline
  visualImage
  visualAlt
  whatIDo {
    __typename
    icon
    label
  }
  credentialFootnote
}
    `;
export const HomepageFeaturedProjectsPartsFragmentDoc = gql`
    fragment HomepageFeaturedProjectsParts on HomepageFeaturedProjects {
  __typename
  projects {
    __typename
    slug
    title
    problem
    whyItMatters
    tags
    thumbnail
    thumbnailAlt
    status
    statusColor
  }
}
    `;
export const HomepageSupportCopyPartsFragmentDoc = gql`
    fragment HomepageSupportCopyParts on HomepageSupportCopy {
  __typename
  heading
  body
  primaryCtaLabel
  primaryCtaHref
  secondaryCtaLabel
  secondaryCtaHref
  footnote
}
    `;
export const ArticleDocument = gql`
    query article($relativePath: String!) {
  article(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ArticleParts
  }
}
    ${ArticlePartsFragmentDoc}`;
export const ArticleConnectionDocument = gql`
    query articleConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ArticleFilter) {
  articleConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ArticleParts
      }
    }
  }
}
    ${ArticlePartsFragmentDoc}`;
export const ProjectDocument = gql`
    query project($relativePath: String!) {
  project(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProjectParts
  }
}
    ${ProjectPartsFragmentDoc}`;
export const ProjectConnectionDocument = gql`
    query projectConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProjectFilter) {
  projectConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProjectParts
      }
    }
  }
}
    ${ProjectPartsFragmentDoc}`;
export const PageDocument = gql`
    query page($relativePath: String!) {
  page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageParts
  }
}
    ${PagePartsFragmentDoc}`;
export const PageConnectionDocument = gql`
    query pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageFilter) {
  pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageParts
      }
    }
  }
}
    ${PagePartsFragmentDoc}`;
export const HomepageHeroDocument = gql`
    query homepageHero($relativePath: String!) {
  homepageHero(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomepageHeroParts
  }
}
    ${HomepageHeroPartsFragmentDoc}`;
export const HomepageHeroConnectionDocument = gql`
    query homepageHeroConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomepageHeroFilter) {
  homepageHeroConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomepageHeroParts
      }
    }
  }
}
    ${HomepageHeroPartsFragmentDoc}`;
export const HomepageFeaturedProjectsDocument = gql`
    query homepageFeaturedProjects($relativePath: String!) {
  homepageFeaturedProjects(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomepageFeaturedProjectsParts
  }
}
    ${HomepageFeaturedProjectsPartsFragmentDoc}`;
export const HomepageFeaturedProjectsConnectionDocument = gql`
    query homepageFeaturedProjectsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomepageFeaturedProjectsFilter) {
  homepageFeaturedProjectsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomepageFeaturedProjectsParts
      }
    }
  }
}
    ${HomepageFeaturedProjectsPartsFragmentDoc}`;
export const HomepageSupportCopyDocument = gql`
    query homepageSupportCopy($relativePath: String!) {
  homepageSupportCopy(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomepageSupportCopyParts
  }
}
    ${HomepageSupportCopyPartsFragmentDoc}`;
export const HomepageSupportCopyConnectionDocument = gql`
    query homepageSupportCopyConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomepageSupportCopyFilter) {
  homepageSupportCopyConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomepageSupportCopyParts
      }
    }
  }
}
    ${HomepageSupportCopyPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      article(variables: ArticleQueryVariables, options?: C): Promise<{data: ArticleQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArticleQueryVariables, query: string}> {
        return requester<{data: ArticleQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArticleQueryVariables, query: string}, ArticleQueryVariables>(ArticleDocument, variables, options);
      },
    articleConnection(variables?: ArticleConnectionQueryVariables, options?: C): Promise<{data: ArticleConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArticleConnectionQueryVariables, query: string}> {
        return requester<{data: ArticleConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArticleConnectionQueryVariables, query: string}, ArticleConnectionQueryVariables>(ArticleConnectionDocument, variables, options);
      },
    project(variables: ProjectQueryVariables, options?: C): Promise<{data: ProjectQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectQueryVariables, query: string}> {
        return requester<{data: ProjectQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectQueryVariables, query: string}, ProjectQueryVariables>(ProjectDocument, variables, options);
      },
    projectConnection(variables?: ProjectConnectionQueryVariables, options?: C): Promise<{data: ProjectConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectConnectionQueryVariables, query: string}> {
        return requester<{data: ProjectConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectConnectionQueryVariables, query: string}, ProjectConnectionQueryVariables>(ProjectConnectionDocument, variables, options);
      },
    page(variables: PageQueryVariables, options?: C): Promise<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}> {
        return requester<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}, PageQueryVariables>(PageDocument, variables, options);
      },
    pageConnection(variables?: PageConnectionQueryVariables, options?: C): Promise<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}> {
        return requester<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}, PageConnectionQueryVariables>(PageConnectionDocument, variables, options);
      },
    homepageHero(variables: HomepageHeroQueryVariables, options?: C): Promise<{data: HomepageHeroQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageHeroQueryVariables, query: string}> {
        return requester<{data: HomepageHeroQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageHeroQueryVariables, query: string}, HomepageHeroQueryVariables>(HomepageHeroDocument, variables, options);
      },
    homepageHeroConnection(variables?: HomepageHeroConnectionQueryVariables, options?: C): Promise<{data: HomepageHeroConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageHeroConnectionQueryVariables, query: string}> {
        return requester<{data: HomepageHeroConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageHeroConnectionQueryVariables, query: string}, HomepageHeroConnectionQueryVariables>(HomepageHeroConnectionDocument, variables, options);
      },
    homepageFeaturedProjects(variables: HomepageFeaturedProjectsQueryVariables, options?: C): Promise<{data: HomepageFeaturedProjectsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageFeaturedProjectsQueryVariables, query: string}> {
        return requester<{data: HomepageFeaturedProjectsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageFeaturedProjectsQueryVariables, query: string}, HomepageFeaturedProjectsQueryVariables>(HomepageFeaturedProjectsDocument, variables, options);
      },
    homepageFeaturedProjectsConnection(variables?: HomepageFeaturedProjectsConnectionQueryVariables, options?: C): Promise<{data: HomepageFeaturedProjectsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageFeaturedProjectsConnectionQueryVariables, query: string}> {
        return requester<{data: HomepageFeaturedProjectsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageFeaturedProjectsConnectionQueryVariables, query: string}, HomepageFeaturedProjectsConnectionQueryVariables>(HomepageFeaturedProjectsConnectionDocument, variables, options);
      },
    homepageSupportCopy(variables: HomepageSupportCopyQueryVariables, options?: C): Promise<{data: HomepageSupportCopyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageSupportCopyQueryVariables, query: string}> {
        return requester<{data: HomepageSupportCopyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageSupportCopyQueryVariables, query: string}, HomepageSupportCopyQueryVariables>(HomepageSupportCopyDocument, variables, options);
      },
    homepageSupportCopyConnection(variables?: HomepageSupportCopyConnectionQueryVariables, options?: C): Promise<{data: HomepageSupportCopyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageSupportCopyConnectionQueryVariables, query: string}> {
        return requester<{data: HomepageSupportCopyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageSupportCopyConnectionQueryVariables, query: string}, HomepageSupportCopyConnectionQueryVariables>(HomepageSupportCopyConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  